import 'package:highschoolhub/main.dart';
import 'package:supabase_flutter/supabase_flutter.dart';

List<List<String>> courses = [
    [
        "Accounting",
        "Business Law",
        "Business Management",
        "Consumer Education",
        "Entrepreneurial Skills",
        "Introduction to Business",
        "Marketing",
        "Personal Finance",
    ], 
    [
        "Animation",
        "App Development",
        "Audio Production",
        "Computer Programming",
        "Computer Repair",
        "Film Production",
        "Graphic Design",
        "Keyboarding",
        "Media Technology",
        "Music Production",
        "Video Game Development",
        "Web Design",
        "Web Programming",
        "Word Processing",
    ], 
    [
        "American Literature",
        "British Literature",
        "Contemporary Literature",
        "Creative Writing",
        "Communication Skills",
        "Debate",
        "English Language and Composition",
        "English Literature and Composition",
        "Humanities",
        "Journalism",
        "Literary Analysis",
        "Modern Literature",
        "Poetry",
        "Popular Literature",
        "Rhetoric",
        "Shakespeare",
        "Technical Writing",
        "World Literature",
        "Written and Oral Communication",
    ], 
    [
        "Chemistry of Foods",
        "CPR Training",
        "Culinary Arts",
        "Early Childhood Development",
        "Early Childhood Education",
        "Family Studies",
        "Fashion and Retail Merchandising",
        "Fashion Construction",
        "Home Economics",
        "Interior Design",
        "Nutrition",
    ], 
    [
        "American Sign Language",
        "Ancient Greek",
        "Arabic",
        "Chinese",
        "French",
        "German",
        "Hebrew",
        "Italian",
        "Japanese",
        "Korean",
        "Latin",
        "Portuguese",
        "Russian",
        "Spanish",
    ], 
    [
        "Algebra 1",
        "Algebra 2",
        "Calculus",
        "Computer Math",
        "Consumer Math",
        "Fundamentals of Math",
        "Geometry",
        "Integrated Math",
        "Math Applications",
        "Multivariable Calculus",
        "Practical Math",
        "Pre-Algebra",
        "Precalculus",
        "Probability",
        "Quantitative Literacy",
        "Statistics",
        "Trigonometry",
    ], 
    [
        "Choir",
        "Concert Band",
        "Dance",
        "Drama",
        "Guitar",
        "Jazz Band",
        "Marching Band",
        "Music Theory",
        "Orchestra",
        "Percussion",
        "Piano",
        "Theater Technology",
        "World Music",
    ], 
    [
        "Aerobics",
        "Dance",
        "Gymnastics",
        "Health",
        "Lifeguard Training",
        "Pilates",
        "Racket Sports",
        "Specialized Sports",
        "Swimming",
        "Weight Training",
        "Yoga",
    ], 
    [
        "Agriculture",
        "Astronomy",
        "Biology",
        "Botany",
        "Chemistry",
        "Earth Science",
        "Electronics",
        "Environmental Science",
        "Environmental Studies",
        "Forensic Science",
        "Geology",
        "Marine Biology",
        "Oceanography",
        "Physical Science",
        "Physics",
        "Zoology",
    ], 
    [
        "Cultural Anthropology",
        "Current Events",
        "European History",
        "Geography",
        "Global Studies",
        "Human Geography",
        "International Relations",
        "Law",
        "Macroeconomics",
        "Microeconomics",
        "Modern World Studies",
        "Physical Anthropology",
        "Political Studies",
        "Psychology",
        "Religious Studies",
        "Sociology",
        "U.S. Government",
        "U.S. History",
        "Women’s Studies",
        "World History",
        "World Politics",
        "World Religions",
    ], 
    [
        "3-D Art",
        "Art History",
        "Ceramics",
        "Digital Media",
        "Drawing",
        "Film Production",
        "Jewelry Design",
        "Painting",
        "Photography",
        "Printmaking",
        "Sculpture",
    ], 
    [
        "Auto Body Repair",
        "Auto Mechanics",
        "Building Construction",
        "Computer-Aided Drafting",
        "Cosmetology",
        "Criminal Justice",
        "Driver Education",
        "Electronics",
        "FFA",
        "Fire Science",
        "Heating and Cooling Systems",
        "Hospitality and Tourism",
        "JROTC",
        "Metalworking",
        "Networking",
        "Plumbing",
        "Production Technology",
        "Refrigeration Fundamentals",
        "Robotics",
        "Woodworking",
    ], 
    [
      "AP Research",
      "AP Seminar",
    ], 
    [
      "AP Art History",
      "AP Music Theory",
    ], 
    [
      "AP English Language and Composition",
      "AP English Literature and Composition",
    ], 
    [
      "AP Comparative Government and Politics",
      "AP European History",
      "AP Human Geography",
      "AP Macroeconomics",
      "AP Microeconomics",
      "AP Psychology",
      "AP United States Government and Politics",
      "AP United States History",
      "AP World History: Modern",
      "AP African American Studies (pilot program)",
    ], 
    [
      "AP Calculus AB",
      "AP Calculus BC",
      "AP Precalculus",
      "AP Statistics",
    ], 
    [
      "AP Computer Science A",
      "AP Computer Science Principles",
    ], 
    [
      "AP Biology",
      "AP Chemistry",
      "AP Environmental Science",
      "AP Physics 1: Algebra-Based",
      "AP Physics 2: Algebra-Based",
      "AP Physics C: Electricity and Magnetism",
      "AP Physics C: Mechanics",
    ],
    [
      "AP Chinese Language and Culture",
      "AP French Language and Culture",
      "AP German Language and Culture",
      "AP Italian Language and Culture",
      "AP Japanese Language and Culture",
      "AP Latin",
      "AP Spanish Language and Culture",
      "AP Spanish Literature and Culture",
    ]
];

List<String> subjects = [
    "Buisness",
    "Computers", 
    "English", 
    "Science", 
    "Language", 
    "Math", 
    "Music", 
    "Sports", 
    "Science", 
    "Social_Studies", 
    "Art", 
    "Electives", 
];

void uploadCladdData() async {
  for(int i = 0; i < subjects.length; i++) {
    print(i);
    for(int k = 0; k < courses[i].length; k++){
      
      await supaBase.from("Classes").insert(
      {
        "ClassName" : courses[i][k],
        "Schools" : [],
        "FieldOfStudy" : subjects[i],
      }
    );
    }
  }
  
}